# Generated by Django 5.1.1 on 2024-11-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='queryhistory',
            options={'verbose_name_plural': 'Query History'},
        ),
        migrations.AlterModelOptions(
            name='scrapehistory',
            options={'verbose_name_plural': 'Scrape History'},
        ),
        migrations.AddField(
            model_name='scrapehistory',
            name='site_url',
            field=models.URLField(default='null'),
        ),
    ]
